# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 41))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_6 = QtWidgets.QMenu(self.menu)
        self.menu_6.setObjectName("menu_6")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_7 = QtWidgets.QMenu(self.menu_4)
        self.menu_7.setObjectName("menu_7")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.actionDakai = QtWidgets.QAction(MainWindow)
        self.actionDakai.setObjectName("actionDakai")
        self.actionZuijin = QtWidgets.QAction(MainWindow)
        self.actionZuijin.setObjectName("actionZuijin")
        self.actionBaocun = QtWidgets.QAction(MainWindow)
        self.actionBaocun.setObjectName("actionBaocun")
        self.actionLingcunwei = QtWidgets.QAction(MainWindow)
        self.actionLingcunwei.setObjectName("actionLingcunwei")
        self.actionFasongdao = QtWidgets.QAction(MainWindow)
        self.actionFasongdao.setObjectName("actionFasongdao")
        self.actionDayin = QtWidgets.QAction(MainWindow)
        self.actionDayin.setObjectName("actionDayin")
        self.actionPianhaoshezhi = QtWidgets.QAction(MainWindow)
        self.actionPianhaoshezhi.setObjectName("actionPianhaoshezhi")
        self.actionTuichu = QtWidgets.QAction(MainWindow)
        self.actionTuichu.setObjectName("actionTuichu")
        self.actionPdf = QtWidgets.QAction(MainWindow)
        self.actionPdf.setObjectName("actionPdf")
        self.actionHtml = QtWidgets.QAction(MainWindow)
        self.actionHtml.setObjectName("actionHtml")
        self.actionPng = QtWidgets.QAction(MainWindow)
        self.actionPng.setObjectName("actionPng")
        self.actionChexiao = QtWidgets.QAction(MainWindow)
        self.actionChexiao.setObjectName("actionChexiao")
        self.actionChongzuo = QtWidgets.QAction(MainWindow)
        self.actionChongzuo.setObjectName("actionChongzuo")
        self.actionJianchagenxgin = QtWidgets.QAction(MainWindow)
        self.actionJianchagenxgin.setObjectName("actionJianchagenxgin")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.action8 = QtWidgets.QAction(MainWindow)
        self.action8.setObjectName("action8")
        self.action9 = QtWidgets.QAction(MainWindow)
        self.action9.setObjectName("action9")
        self.action10 = QtWidgets.QAction(MainWindow)
        self.action10.setObjectName("action10")
        self.action11 = QtWidgets.QAction(MainWindow)
        self.action11.setObjectName("action11")
        self.action12 = QtWidgets.QAction(MainWindow)
        self.action12.setObjectName("action12")
        self.action1_3 = QtWidgets.QAction(MainWindow)
        self.action1_3.setObjectName("action1_3")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action3_2 = QtWidgets.QAction(MainWindow)
        self.action3_2.setObjectName("action3_2")
        self.action1_4 = QtWidgets.QAction(MainWindow)
        self.action1_4.setObjectName("action1_4")
        self.action2_3 = QtWidgets.QAction(MainWindow)
        self.action2_3.setObjectName("action2_3")
        self.action3_3 = QtWidgets.QAction(MainWindow)
        self.action3_3.setObjectName("action3_3")
        self.action4_2 = QtWidgets.QAction(MainWindow)
        self.action4_2.setObjectName("action4_2")
        self.action1_5 = QtWidgets.QAction(MainWindow)
        self.action1_5.setObjectName("action1_5")
        self.action2_4 = QtWidgets.QAction(MainWindow)
        self.action2_4.setObjectName("action2_4")
        self.action1_6 = QtWidgets.QAction(MainWindow)
        self.action1_6.setObjectName("action1_6")
        self.action2_5 = QtWidgets.QAction(MainWindow)
        self.action2_5.setObjectName("action2_5")
        self.action3_4 = QtWidgets.QAction(MainWindow)
        self.action3_4.setObjectName("action3_4")
        self.action4_3 = QtWidgets.QAction(MainWindow)
        self.action4_3.setObjectName("action4_3")
        self.action1_7 = QtWidgets.QAction(MainWindow)
        self.action1_7.setObjectName("action1_7")
        self.action2_6 = QtWidgets.QAction(MainWindow)
        self.action2_6.setObjectName("action2_6")
        self.action3_5 = QtWidgets.QAction(MainWindow)
        self.action3_5.setObjectName("action3_5")
        self.action4_4 = QtWidgets.QAction(MainWindow)
        self.action4_4.setObjectName("action4_4")
        self.action5_2 = QtWidgets.QAction(MainWindow)
        self.action5_2.setObjectName("action5_2")
        self.action6_2 = QtWidgets.QAction(MainWindow)
        self.action6_2.setObjectName("action6_2")
        self.action7_2 = QtWidgets.QAction(MainWindow)
        self.action7_2.setObjectName("action7_2")
        self.actionDangqian = QtWidgets.QAction(MainWindow)
        self.actionDangqian.setObjectName("actionDangqian")
        self.actionQuanxiangmu = QtWidgets.QAction(MainWindow)
        self.actionQuanxiangmu.setObjectName("actionQuanxiangmu")
        self.actionH1 = QtWidgets.QAction(MainWindow)
        self.actionH1.setObjectName("actionH1")
        self.actionH2 = QtWidgets.QAction(MainWindow)
        self.actionH2.setObjectName("actionH2")
        self.actionH3 = QtWidgets.QAction(MainWindow)
        self.actionH3.setObjectName("actionH3")
        self.actionH4 = QtWidgets.QAction(MainWindow)
        self.actionH4.setObjectName("actionH4")
        self.actionH5 = QtWidgets.QAction(MainWindow)
        self.actionH5.setObjectName("actionH5")
        self.actionH6 = QtWidgets.QAction(MainWindow)
        self.actionH6.setObjectName("actionH6")
        self.menu_6.addAction(self.actionPdf)
        self.menu_6.addAction(self.actionHtml)
        self.menu_6.addAction(self.actionPng)
        self.menu.addAction(self.action1)
        self.menu.addAction(self.actionDakai)
        self.menu.addAction(self.actionZuijin)
        self.menu.addSeparator()
        self.menu.addAction(self.actionBaocun)
        self.menu.addAction(self.actionLingcunwei)
        self.menu.addSeparator()
        self.menu.addAction(self.actionFasongdao)
        self.menu.addAction(self.menu_6.menuAction())
        self.menu.addAction(self.actionDayin)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPianhaoshezhi)
        self.menu.addSeparator()
        self.menu.addAction(self.actionTuichu)
        self.menu_2.addAction(self.actionChexiao)
        self.menu_2.addAction(self.actionChongzuo)
        self.menu_3.addAction(self.actionDangqian)
        self.menu_3.addAction(self.actionQuanxiangmu)
        self.menu_7.addAction(self.actionH1)
        self.menu_7.addAction(self.actionH2)
        self.menu_7.addAction(self.actionH3)
        self.menu_7.addAction(self.actionH4)
        self.menu_7.addAction(self.actionH5)
        self.menu_7.addAction(self.actionH6)
        self.menu_4.addAction(self.action1_2)
        self.menu_4.addAction(self.action2)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action3)
        self.menu_4.addAction(self.menu_7.menuAction())
        self.menu_4.addAction(self.action5)
        self.menu_4.addAction(self.action6)
        self.menu_4.addAction(self.action7)
        self.menu_4.addAction(self.action8)
        self.menu_4.addAction(self.action9)
        self.menu_4.addAction(self.action10)
        self.menu_4.addAction(self.action11)
        self.menu_4.addAction(self.action12)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action1_3)
        self.menu_4.addAction(self.action2_2)
        self.menu_4.addAction(self.action3_2)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action1_4)
        self.menu_4.addAction(self.action2_3)
        self.menu_4.addAction(self.action3_3)
        self.menu_4.addAction(self.action4_2)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action1_5)
        self.menu_4.addAction(self.action2_4)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action1_6)
        self.menu_4.addAction(self.action2_5)
        self.menu_4.addAction(self.action3_4)
        self.menu_4.addAction(self.action4_3)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action1_7)
        self.menu_4.addAction(self.action2_6)
        self.menu_4.addAction(self.action3_5)
        self.menu_4.addAction(self.action4_4)
        self.menu_4.addAction(self.action5_2)
        self.menu_4.addAction(self.action6_2)
        self.menu_4.addAction(self.action7_2)
        self.menu_5.addAction(self.actionJianchagenxgin)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_6.setTitle(_translate("MainWindow", "导出到"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "查找"))
        self.menu_4.setTitle(_translate("MainWindow", "插入"))
        self.menu_7.setTitle(_translate("MainWindow", "标题"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.action1.setText(_translate("MainWindow", "新建"))
        self.actionDakai.setText(_translate("MainWindow", "打开文件"))
        self.actionZuijin.setText(_translate("MainWindow", "最近文档"))
        self.actionBaocun.setText(_translate("MainWindow", "保存"))
        self.actionLingcunwei.setText(_translate("MainWindow", "另存为"))
        self.actionFasongdao.setText(_translate("MainWindow", "发送到"))
        self.actionDayin.setText(_translate("MainWindow", "打印"))
        self.actionPianhaoshezhi.setText(_translate("MainWindow", "偏好设置"))
        self.actionTuichu.setText(_translate("MainWindow", "退出"))
        self.actionPdf.setText(_translate("MainWindow", "pdf"))
        self.actionHtml.setText(_translate("MainWindow", "html"))
        self.actionPng.setText(_translate("MainWindow", "png"))
        self.actionChexiao.setText(_translate("MainWindow", "撤销"))
        self.actionChongzuo.setText(_translate("MainWindow", "重做"))
        self.actionJianchagenxgin.setText(_translate("MainWindow", "检查更新"))
        self.action1_2.setText(_translate("MainWindow", "当前日期时间"))
        self.action2.setText(_translate("MainWindow", "当前文件名"))
        self.action3.setText(_translate("MainWindow", "Markdown"))
        self.action5.setText(_translate("MainWindow", "加粗"))
        self.action6.setText(_translate("MainWindow", "强调"))
        self.action7.setText(_translate("MainWindow", "行内代码"))
        self.action8.setText(_translate("MainWindow", "图片"))
        self.action9.setText(_translate("MainWindow", "超链接"))
        self.action10.setText(_translate("MainWindow", "引用"))
        self.action11.setText(_translate("MainWindow", "有序列表"))
        self.action12.setText(_translate("MainWindow", "无序列表"))
        self.action1_3.setText(_translate("MainWindow", "分页符"))
        self.action2_2.setText(_translate("MainWindow", "分节符"))
        self.action3_2.setText(_translate("MainWindow", "分段符"))
        self.action1_4.setText(_translate("MainWindow", "github"))
        self.action2_3.setText(_translate("MainWindow", "代码块"))
        self.action3_3.setText(_translate("MainWindow", "删除线"))
        self.action4_2.setText(_translate("MainWindow", "Tasklist"))
        self.action1_5.setText(_translate("MainWindow", "MultiMarkdown"))
        self.action2_4.setText(_translate("MainWindow", "下划线"))
        self.action1_6.setText(_translate("MainWindow", "PHP"))
        self.action2_5.setText(_translate("MainWindow", "脚注"))
        self.action3_4.setText(_translate("MainWindow", "脚注引用"))
        self.action4_3.setText(_translate("MainWindow", "表格"))
        self.action1_7.setText(_translate("MainWindow", "自定义"))
        self.action2_6.setText(_translate("MainWindow", "高亮"))
        self.action3_5.setText(_translate("MainWindow", "嵌入对象"))
        self.action4_4.setText(_translate("MainWindow", "数学代码(行间)"))
        self.action5_2.setText(_translate("MainWindow", "数学代码(行内)"))
        self.action6_2.setText(_translate("MainWindow", "注释"))
        self.action7_2.setText(_translate("MainWindow", "目录"))
        self.actionDangqian.setText(_translate("MainWindow", "搜索当前"))
        self.actionQuanxiangmu.setText(_translate("MainWindow", "搜索全部"))
        self.actionH1.setText(_translate("MainWindow", "H1    #"))
        self.actionH2.setText(_translate("MainWindow", "H2    ##"))
        self.actionH3.setText(_translate("MainWindow", "H3    ###"))
        self.actionH4.setText(_translate("MainWindow", "H4    ####"))
        self.actionH5.setText(_translate("MainWindow", "H5    #####"))
        self.actionH6.setText(_translate("MainWindow", "H6    ######"))


